name: multiply-prior-engine

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.6*
  #
  # runtime dependencies
#
  - numpy=1.16
  - shapely=1.6.4
  - h5py=2.8
  - pandas=0.22
  - scipy=1.2.1
  - setuptools=40.8
  - matplotlib=2.2
  - pytest=4.6
  - gdal=2.4
  - netCDF4=1.5
  - PyYAML=3.12
  - typing
  - pip
  - pip:
    - python_dateutil
    - recommonmark
    - m2r
    - sphinx_rtd_theme
